/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const computed: typeof import('vue')['computed']
  const defineEmits: typeof import('vue')['defineEmits']
  const defineProps: typeof import('vue')['defineProps']
  const hasOwn: typeof import('@/shared/general')['hasOwn']
  const isArray: typeof import('@/shared/general')['isArray']
  const isFunction: typeof import('@/shared/general')['isFunction']
  const isMap: typeof import('@/shared/general')['isMap']
  const isObject: typeof import('@/shared/general')['isObject']
  const isPlainObject: typeof import('@/shared/general')['isPlainObject']
  const isPromise: typeof import('@/shared/general')['isPromise']
  const isRegExp: typeof import('@/shared/general')['isRegExp']
  const isSet: typeof import('@/shared/general')['isSet']
  const isString: typeof import('@/shared/general')['isString']
  const isSymbol: typeof import('@/shared/general')['isSymbol']
  const nextTick: typeof import('vue')['nextTick']
  const onActivated: typeof import('vue')['onActivated']
  const onBeforeUnmount: typeof import('vue')['onBeforeUnmount']
  const onDeactivated: typeof import('vue')['onDeactivated']
  const onMounted: typeof import('vue')['onMounted']
  const reactive: typeof import('vue')['reactive']
  const ref: typeof import('vue')['ref']
  const toTypeString: typeof import('@/shared/general')['toTypeString']
  const watch: typeof import('vue')['watch']
}
